name: .NET Windows Build

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: false

      - name: Install .NET
        uses: actions/setup-dotnet@v3

      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Application
          path: ./bin/Release/net5.0/*
